name: TurnLab
options:
  bundleIdPrefix: com.turnlab
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    DEVELOPMENT_TEAM: ARPUVY7JZ9
    CODE_SIGN_STYLE: Automatic

targets:
  TurnLab:
    type: application
    platform: iOS
    sources:
      - path: TurnLab
        excludes:
          - "**/.DS_Store"
          - "Resources/Content"
      - path: TurnLab/Resources/Assets.xcassets
        buildPhase: resources
    resources:
      - path: TurnLab/Resources/Content
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.turnlab.app
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Turn Lab
        INFOPLIST_KEY_CFBundleIconName: AppIcon
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: TurnLab/TurnLab.entitlements
    dependencies:
      - target: TurnLabWidget
        embed: true

  TurnLabWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: TurnLabWidget
        excludes:
          - "**/.DS_Store"
          - "Info.plist"
    info:
      path: TurnLabWidget/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.turnlab.app.widget
        CODE_SIGN_ENTITLEMENTS: TurnLabWidget/TurnLabWidget.entitlements
        SKIP_INSTALL: YES

  TurnLabTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TurnLabTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.turnlab.app.tests
    dependencies:
      - target: TurnLab

  TurnLabUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: TurnLabUITests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.turnlab.app.uitests
    dependencies:
      - target: TurnLab

schemes:
  TurnLab:
    build:
      targets:
        TurnLab: all
        TurnLabWidget: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TurnLabTests
        - TurnLabUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
