# Snapfile for Turn Lab screenshots

devices([
  # iPhone devices (6.7" and 6.1" displays)
  "iPhone 15 Pro Max",
  "iPhone 15 Pro",
  "iPhone SE (3rd generation)",
  # iPad devices (12.9" and 11" displays for App Store)
  "iPad Pro (12.9-inch) (6th generation)",
  "iPad Pro (11-inch) (4th generation)"
])

languages([
  "en-US"
])

scheme("TurnLab")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
