# Snapfile for Turn Lab screenshots

devices([
  "iPhone 15 Pro Max",
  "iPhone 15 Pro",
  "iPhone SE (3rd generation)"
])

languages([
  "en-US"
])

scheme("TurnLab")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
